name: Rust

on:
  push:
    workflow_dispatch:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GH_TOKEN: ${{ GITHUB.TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && sudo apt-get update && sudo apt-get upgrade && sudo apt install build-essential  && rustup default nightly && cargo update && cargo build --verbose

